# Generated by Django 5.0.6 on 2024-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocations',
            name='village',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverylocations',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
