# Generated by Django 5.0.6 on 2024-09-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliverylocations_village_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocations',
            name='community',
            field=models.CharField(default='', max_length=50),
        ),
    ]
