# Generated by Django 5.0.6 on 2024-09-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverylocations_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylocations',
            name='village',
            field=models.CharField(default='', max_length=50),
        ),
    ]
