# Generated by Django 5.0.6 on 2024-09-05 20:59

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='')),
                ('img', models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, unique=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('discount_price', models.IntegerField(default=0)),
                ('wholesale_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('is_in_cart', models.BooleanField(default=False)),
                ('cart_id', models.UUIDField(default=uuid.uuid4)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_store.color')),
            ],
        ),
        migrations.CreateModel(
            name='CartColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.cart')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.color')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomersAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=300)),
                ('apartment', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number  must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Nigeria', max_length=20)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('reference', models.CharField(default='', max_length=50)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_refund_request', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 9, 5, 21, 59, 6, 293128))),
                ('delivery_status', models.CharField(choices=[('processing', 'processing'), ('in_progress', 'in_progress'), ('delivered', 'delivered')], default='Processing', max_length=255)),
                ('cart_id', models.UUIDField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_store.coupon')),
                ('delivery_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliverylocations')),
                ('product', models.ManyToManyField(to='book_store.cart')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_store.customersaddress')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book_store.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('additional_information', models.TextField(default='', max_length=1000)),
                ('feature1', models.CharField(blank=True, max_length=255, null=True)),
                ('feature2', models.CharField(blank=True, max_length=255, null=True)),
                ('feature3', models.CharField(blank=True, max_length=255, null=True)),
                ('feature4', models.CharField(blank=True, max_length=255, null=True)),
                ('feature5', models.CharField(blank=True, max_length=255, null=True)),
                ('feature6', models.CharField(blank=True, max_length=255, null=True)),
                ('feature7', models.CharField(blank=True, max_length=255, null=True)),
                ('feature8', models.CharField(blank=True, max_length=255, null=True)),
                ('feature10', models.CharField(blank=True, max_length=255, null=True)),
                ('specification1', models.CharField(blank=True, max_length=255, null=True)),
                ('specification2', models.CharField(blank=True, max_length=255, null=True)),
                ('specification3', models.CharField(blank=True, max_length=255, null=True)),
                ('specification4', models.CharField(blank=True, max_length=255, null=True)),
                ('specification5', models.CharField(blank=True, max_length=255, null=True)),
                ('specification6', models.CharField(blank=True, max_length=255, null=True)),
                ('specification7', models.CharField(blank=True, max_length=255, null=True)),
                ('specification8', models.CharField(blank=True, max_length=255, null=True)),
                ('specification9', models.CharField(blank=True, max_length=255, null=True)),
                ('specification10', models.CharField(blank=True, max_length=255, null=True)),
                ('img_1', models.ImageField(default='img', upload_to='static/media/img')),
                ('img_2', models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img')),
                ('img_3', models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img')),
                ('img_4', models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img')),
                ('label', models.CharField(blank=True, choices=[('label-new', 'new'), ('label-out', 'out'), ('label-top', 'top'), ('label-sale', 'sale')], default='', max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], default='female', max_length=10, null=True)),
                ('display_on_home_page', models.BooleanField(default=False)),
                ('is_banner', models.BooleanField(default=False)),
                ('is_best_selling', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='eg-product-title', unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deal_of_the_day', models.BooleanField(default=False)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('minimum_order', models.IntegerField(default=1)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='book_store.product'),
        ),
        migrations.CreateModel(
            name='ProductSizeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='book_store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='book_store.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='book_store.size')),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(through='book_store.ProductSizeColor', to='book_store.color'),
        ),
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='')),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.order')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='products', through='book_store.ProductSizeColor', to='book_store.size'),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_store.size'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_store.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='book_store.product')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product', 'session_key')},
            },
        ),
    ]
