# Generated by Django 5.0.6 on 2024-09-09 17:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='product_colors',
            field=models.ManyToManyField(related_name='size_colors', through='book_store.ProductSizeColor', to='book_store.color'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 18, 18, 43, 738840)),
        ),
        migrations.AlterField(
            model_name='productsizecolor',
            name='color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='color_product_colors', to='book_store.color'),
        ),
        migrations.AlterField(
            model_name='productsizecolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size_colors', to='book_store.product'),
        ),
        migrations.AlterField(
            model_name='productsizecolor',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_product_colors', to='book_store.size'),
        ),
    ]
