# Generated by Django 5.0.6 on 2024-07-28 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_color_alter_coupon_valid_from_alter_coupon_valid_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='img',
            field=models.ImageField(blank=True, default='img', null=True, upload_to='static/media/img'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 10, 13, 16, 214769, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 28, 10, 13, 16, 214769, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 11, 13, 16, 214769)),
        ),
        migrations.DeleteModel(
            name='ProductColorQuantity',
        ),
    ]
