# Generated by Django 4.2.9 on 2024-10-10 21:57

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersaddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 22, 57, 37, 997369)),
        ),
    ]
