# Generated by Django 5.0.6 on 2024-07-28 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0004_color_is_available_color_quantity_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 11, 21, 49, 261922, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 28, 11, 21, 49, 261922, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 12, 21, 49, 261922)),
        ),
    ]
