# Generated by Django 5.0.6 on 2024-09-19 20:09

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0004_emailsubscription_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersaddress',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NG'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 21, 9, 23, 421063)),
        ),
    ]
