# Generated by Django 4.2.9 on 2024-10-10 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_alter_customersaddress_country_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 23, 39, 10, 789294)),
        ),
    ]
