# Generated by Django 5.0.6 on 2024-07-29 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_product_minimum_order_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='book_store.color'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 10, 16, 10, 192645, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 29, 10, 16, 10, 192645, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 11, 16, 10, 192645)),
        ),
    ]
