# Generated by Django 5.0.6 on 2024-09-21 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0006_alter_customersaddress_user_alter_order_date_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 13, 5, 5, 586528)),
        ),
    ]
