# Generated by Django 5.0.6 on 2024-07-30 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_alter_cart_color_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='color',
            new_name='colors',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 18, 31, 11, 118479, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 30, 18, 31, 11, 118479, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 19, 31, 11, 118479)),
        ),
    ]
