# Generated by Django 5.0.6 on 2024-09-23 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 18, 26, 14, 597373)),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
