# Generated by Django 4.2.9 on 2024-10-12 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0008_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_information',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 19, 6, 19, 992702)),
        ),
    ]
