# Generated by Django 4.2.9 on 2024-10-13 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0009_remove_product_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 0, 32, 17, 370386)),
        ),
    ]
