# Generated by Django 5.0.6 on 2024-08-02 14:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0010_alter_cartcolor_quantity_alter_coupon_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 14, 51, 43, 42866, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 2, 14, 51, 43, 42866, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='customersaddress',
            name='telephone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number  must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 15, 51, 43, 42866)),
        ),
    ]
