# Generated by Django 5.0.6 on 2024-09-24 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0010_profile_country_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersaddress',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customersaddress',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customersaddress',
            name='town',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 11, 55, 22, 360736)),
        ),
    ]
