# Generated by Django 5.0.6 on 2024-08-28 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0010_order_invoice_number_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 13, 42, 24, 327212)),
        ),
    ]
