# Generated by Django 5.0.6 on 2024-09-24 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0011_customersaddress_city_alter_customersaddress_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 15, 2, 57, 701859)),
        ),
    ]
