name: Deploy Django to cPanel

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest

    steps:
    # Check out the latest code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Adjust the Python version if necessary

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Collect static files for Django (required for deployment)
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    # Deploy via FTP/SFTP to cPanel
    - name: Deploy to cPanel using FTP
      uses: SamKirkland/FTP-Deploy-Action@v4  # Corrected version
      with:
        ftp-server: ${{ secrets.CPANEL_FTP_SERVER }}
        ftp-username: ${{ secrets.CPANEL_FTP_USERNAME }}
        ftp-password: ${{ secrets.CPANEL_FTP_PASSWORD }}
        ftp-port: ${{ secrets.CPANEL_FTP_PORT }}
        local-dir: ./  # Adjust this if necessary (e.g., public folder)
        server-dir: aajomos.com/public_html/  # Your cPanel deployment directory (adjust as needed)
        method: "sync"  # Optional, to sync files and remove old ones not in your repo
