name: Build and deploy to cPanel via lftp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python (if needed)
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      # Install dependencies (if needed)
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
  
      - name: Install django
        run: pip install django
      # Collect static files (if using Django or similar frameworks)
      - name: Collect static files
        run: python manage.py collectstatic --noinput

      # Install lftp for FTP deployment
      - name: Install lftp
        run: sudo apt-get install lftp -y

      # Deploy to cPanel using lftp
      - name: Deploy via lftp
        env:
          FTP_HOST: ${{ secrets.CPANEL_FTP_HOST }}
          FTP_USER: ${{ secrets.CPANEL_FTP_USER }}
          FTP_PASS: ${{ secrets.CPANEL_FTP_PASS }}
          FTP_PORT: ${{ secrets.CPANEL_FTP_PORT }}
        run: |
          lftp -c "
          set ftp:ssl-allow true;
          set ftp:ssl-force true;
          set net:max-retries 2;           # Retry twice in case of network issues
          set net:persist-retries true;    # Keep trying to reconnect
          set net:timeout 30;              # 30 seconds timeout for connections
          set net:reconnect-interval-base 5;
          set net:reconnect-interval-max 30;
          open -u $FTP_USER,$FTP_PASS $FTP_HOST;
          mirror -R ./ /public_html --delete --parallel=10"
